import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import '../models/report_model.dart';
import '../models/simulation_model.dart';
import '../models/metrics_model.dart';
import '../models/optimization_model.dart';

class ReportService {
  Future<File> generatePdfReport(NetworkReport report) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        build: (context) => [
          _buildHeader(report),
          if (report.simulation != null) _buildSimulationSection(context, report.simulation!),
          if (report.metrics != null && report.metrics!.isNotEmpty)
            _buildMetricsSection(report.metrics!),
          if (report.optimization != null) _buildOptimizationSection(report.optimization!),
          _buildFooter(report),
        ],
      ),
    );

    final output = await getApplicationDocumentsDirectory();
    final file = File("${output.path}/${report.fileName}");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  pw.Widget _buildHeader(NetworkReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          report.title,
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          'Generated on: ${report.generatedAt.toString()}',
          style: const pw.TextStyle(fontSize: 10),
        ),
        pw.Divider(),
      ],
    );
  }

  pw.Widget _buildSimulationSection(pw.Context context, SimulationResults simulation) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Header(
          level: 1,
          text: 'Simulation Results',
        ),
        pw.Table.fromTextArray(
          context: context,
          data: [
            ['Parameter', 'Value'],
            ['User Density', '${simulation.parameters.userDensity} users/km²'],
            ['Building Density', simulation.parameters.buildingDensity.toStringAsFixed(2)],
            ['Frequency', '${simulation.parameters.frequency} GHz'],
            ['TX Power', '${simulation.parameters.txPower} dBm'],
            ['Base Stations', simulation.parameters.numBaseStations.toString()],
            ['Received Power', '${simulation.receivedPower.toStringAsFixed(2)} dBm'],
            ['Path Loss', '${simulation.pathLoss.toStringAsFixed(2)} dB'],
            ['SINR', '${simulation.sinr.toStringAsFixed(2)} dB'],
            ['Latency', '${simulation.latency.toStringAsFixed(2)} ms'],
          ],
        ),
        pw.SizedBox(height: 20),
      ],
    );
  }

  pw.Widget _buildMetricsSection(List<NetworkMetrics> metrics) {
    final avgSignal = metrics.map((m) => m.signalStrength).reduce((a, b) => a + b) / metrics.length;
    final avgLatency = metrics.map((m) => m.latency).reduce((a, b) => a + b) / metrics.length;

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Header(
          level: 1,
          text: 'Network Metrics',
        ),
        pw.Text('Metrics collected: ${metrics.length} samples'),
        pw.Text('Average Signal Strength: ${avgSignal.toStringAsFixed(2)} dBm'),
        pw.Text('Average Latency: ${avgLatency.toStringAsFixed(2)} ms'),
        pw.SizedBox(height: 20),
      ],
    );
  }

  pw.Widget _buildOptimizationSection(OptimizationResult optimization) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Header(
          level: 1,
          text: 'Optimization Suggestions',
        ),
        ...optimization.suggestions.map((s) => pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                s.description,
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text('Priority: ${s.priority}'),
            ],
          ),
        )),
      ],
    );
  }

  pw.Widget _buildFooter(NetworkReport report) {
    return pw.Center(
      child: pw.Text(
        'Report generated by Wireless Network Evaluator',
        style: const pw.TextStyle(fontSize: 10),
      ),
    );
  }
}